# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86ac9808e7f4127c0059eef2f1b0b74ea718fb8b1914aed2108ae4f205292f71fc97ed772e9ad0530e1ef55ce567bd963f571208455179e4ac8c4862076b11f5

test:
  secret_key_base: 002fc64f12bae52faf26ebe85c6e998ef66a7489b361987fbb3b247f1e4dfb449299359ee49dc200f6d40fb2ab3d9e5f086439971f62baf6ab53bb73b77b39a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
